### ISSUE TITLE
Can't Take Screenshots in Linux

### ISSUE THREAD

**Issue by ryanlarkin** [AstechzGO/Luminescent#55]
When pressing F2 in Linux (Ubuntu 14.04), the game freezes.  This may be an issue in other platforms.  Also screenshots do work on Windows.

Log:

[main/SEVERE]: java.lang.IllegalArgumentException: Number of remaining buffer elements is 6220800, must be at least 8294400. Because at most 8294400 elements can be returned, a buffer with at least 8294400 elements is required, regardless of actual returned element count
    at org.lwjgl.BufferChecks.throwBufferSizeException(BufferChecks.java:162)
    at org.lwjgl.BufferChecks.checkBufferSize(BufferChecks.java:189)
    at org.lwjgl.BufferChecks.checkBuffer(BufferChecks.java:230)
    at org.lwjgl.opengl.GL11.glReadPixels(GL11.java:2450)
    at astechzgo.luminescent.utils.DisplayUtils.takeScreenshot(DisplayUtils.java:128)
    at astechzgo.luminescent.main.Luminescent.Tick(Luminescent.java:176)
    at astechzgo.luminescent.main.Main.Tick(Main.java:79)
    at astechzgo.luminescent.main.Main.Run(Main.java:29)
    at astechzgo.luminescent.main.Main.main(Main.java:20)

**Comment by ghost** [comment]
That's possibly because before compiling and exporting you need to set the current native to linux. If that doesn't work then I'm not quite sure.

**Comment by ryanlarkin** [comment]
May be fixed by #57 if upgrading to LWJGL 3.  Haven't tested though.

**Comment by ryanlarkin** [comment]
Fixed by #60
